/*
    Copyright 2021: Samuel Dominic Chukwuemeka (Samdom For Peace)
    https://scholarlycommunication.github.io/Presentations/Projects/PreCalculus/PiecewiseFunctions/FederalTax.html
    message 9
*/

/*
var date = new Date();
var day = date.getDate(); 

var dailyMessage = new Array(
        ' "In the beginning GOD created the heavens and the earth. Now the earth was formless and void, and darkness was over the surface of the deep. And the SPIRIT of GOD was hovering over the surface of the waters. And GOD said, \"Let there be light,\" and there was light. And seeing that the light was good, GOD separated the light from the darkness. GOD called the light \"day\", and the darkness He called \"night\". And there was evening, and there was morning - the first day." - Genesis 1:1 - 5 ',
        ' "And GOD said, \"Let there be an expanse between the waters, to separate the waters from the waters.\" So GOD made the expanse and separated the waters beneath it from the waters above. And it was so. GOD called the expanse \"sky.\" And there was evening, and there was morning - the second day." - Genesis 1:6 - 8 ',
        ' "And GOD said, \"Let the waters under the sky be gathered into one place, and so that the dry land may appear.\" And it was so. GOD called the dry land \"earth,\" and the gathering of waters, He called \"seas.\" And GOD saw that it was good. Then GOD said, \"Let the earth bring forth vegetation: seed-bearing plants and fruit trees, each bearing fruit with seed according to its kind.\" And it was so. The earth produced vegetation: seed-bearing plants according to their kinds and trees bearing fruit with seed according to their kinds. And GOD saw that it was good. And there was evening, and there was morning - the third day." - Genesis 1:9 - 13 ',
        ' "And GOD said, \"Let there be lights in the expanse of the sky to distinguish between the day and the night, and let them be signs to mark the seasons and days and years, And let them serve as lights in the expanse of the sky to shine upon the earth.\" And it was so. GOD made two great lights: the greater light to rule the day and the lesser light to rule the night. And He made the stars as well. GOD set these lights in the expanse of the sky to shine upon the earth, to preside over the day and the night, and to separate the light from the darkness. And GOD saw that it was good. And there was evening, and there was morning - the fourth day." - Genesis 1:14 - 19 ',
        ' "And GOD said, \"Let the waters teem with living creatures, and let birds fly above the earth in the open expanse of the sky.\" So GOD created the great sea creatures and every living thing that moves, with which the waters teemed according to their kinds, and every bird of flight after its kind. And GOD saw that it was good. Then GOD blessed them and said, \"be fruitful and multiply and fill the waters of the seas, and let birds multiply on the earth.\" And there was evening, and there was morning - the fifth day." - Genesis 1:20 - 23 ',
        ' "And GOD said, \"Let the earth bring forth living creatures according to their kinds: livestock, land crawlers, and beasts of the earth according to their kinds.\" And it was so. GOD made the beasts of the earth according to their kinds, the livestock according to their kinds, and everything that crawls upon the earth according to its kind. And GOD saw that it was good." - Genesis 1:24 - 25 ',
        ' "Then GOD said, \"Let Us make man in Our image, after Our likeness, to rule over the fish of the sea and the birds of the air, over the livestock, and over all the earth itself and every creature that crawls upon it.\" So GOD created man in His Own image; in the image of GOD He created him; male and female He created them. GOD blessed them and said to them, \"Be fruitful and multiply, and fill the earth and subdue it; rule over the fish of the sea and the birds of the air and every creature that crawls upon the earth.\" Then GOD said, \"Behold, I have given you every seed-bearing plant on the face of all the earth, and every tree whose fruit contains seed. They will be yours for food. And to every beast of the earth and every bird of the air and every creature that crawls upon the earth - everything that has the breath of life in it - I have given every green plant for food.\" And it was so. And GOD looked upon all that He had made, and indeed, it was very good. And there was evening, and there was morning - the sixth day." - Genesis 1:26 - 31 ',
        ' "Thus the heavens and the earth were completed in all their vast array. And by the seventh day, GOD had finished the work He had been doing; so on that day, He rested from all His work. Then GOD blessed the seventh day and sanctified it, because on that day, He rested from all the work of creation that He had accomplished. This is the account of the heavens and the earth when they were created, in the day that the LORD GOD made them." - Genesis 2:1 - 4 ',
        ' "So then, this is how you should pray: Our FATHER in heaven, hallowed be Your Name, Your kingdom come, Your will be done on earth as it is in heaven. Give us this day our daily bread. And forgive us our debts, as we also have forgiven our debtors. And lead us not to the test, but deliver us from all evil." - Matthew 6: 9 - 13 ',
        ' O LORD my GOD, please bless me always with 1 Samuel 2:26 and Luke 2:52. Amen. ',
        ' "From where does my help come? My help comes from the LORD, the Maker of heaven and earth. He will not allow my foot to slip; my Protector will not slumber. Behold, the Protector of Israel will not slumber or sleep. The LORD is my keeper; the LORD is the shade on my right hand. The sun will not strike me by day nor the moon by night. The LORD will guard me from all evil. He will preserve my soul. The LORD will watch over my going out and my coming in, both now and forevermore." - Psalm 121 ',
        ' "For we do not proclaim ourselves, but JESUS CHRIST as LORD, and ourselves as your servants for JESUS\' sake. For GOD, who said, \"Let light shine out of darkness,\" made His light shine in our hearts to give us the light of the knowledge of the glory of GOD in the face of JESUS CHRIST. Now, we have this treasure in jars of clay to show that this surpassingly great power is from GOD and not from us. We are pressed on all sides, but not crushed; perplexed but not in despair; persecuted but not forsaken; struck down but not destroyed. We always carry around in our body the death of JESUS CHRIST, so that the life of JESUS CHRIST may also be revealed in our body."  - 2 Corinthians 4:5-10',
        ' "Give praise, O servants of the LORD; praise the name of the LORD. Blessed be the name of the LORD both now and forever. From the rising to the setting of the sun, the name of the LORD is praised. The LORD is exalted over all the nations, His glory above the heavens. Who is like the LORD our GOD, the One enthroned on high? He humbles Himself to behold the heavens and the earth. He raises the poor from the dust and lifts the needy from the dump to seat them with nobles, with the princes of His people. He settles the barren woman in her home, as a joyful mother to her children. Alleluia!" - Psalm 113 ',
        ' "When JESUS saw the crowds, He went up on the mountain and sat down. His disciples came to Him, and He began to teach them, saying: \"Blessed are the poor in spirit, for theirs is the kingdom of heaven. Blessed are those who mourn, for they will be comforted. Blessed are the meek, for they will inherit the earth. Blessed are those who hunger and thirst for righteousness, for they will be filled. Blessed are the merciful, for they will be shown mercy. Blessed are the pure in heart, for they will see GOD. Blessed are the peacemakers, for they will be called sons of GOD. Blessed are those who are persecuted because of righteousness, for theirs is the kingdom of heaven. Blessed are you when people insult you, persecute you, and falsely say all kinds of evil against you because of Me. Rejoice and be glad, because great is your reward in heaven; for in the same way they persecuted the prophets before you." - Matthew 5:1 - 12 ',
        ' "The proverbs of Solomon, son of David, king of Israel: To know wisdom and discipline; to comprehend the words of insight; to receive instruction in wise living, in righteousness, justice, and equity; to impart prudence to the simple, knowledge and discretion to the young - let the wise listen and gain instruction, and the discerning acquire wise counsel - to understand the proverbs and parables, the sayings and riddles of the wise. The fear of the LORD is the beginning of knowledge, but fools despise wisdom and discipline. Listen, my son, to your father\'s instruction (if they are good), and do not forsake the teaching of your mother (if they are good). For they are a garland of grace on your head, and a pendant around your neck. My son, if sinners entice you, do not yield to them. If they say, \"Come along, let us lie in wait for blood, let us ambush the innocent without cause, let us swallow them alive like sheol, and whole like those descending into the pit. We will find all manner of precious goods; we will fill our houses with plunder. Throw in your lot with us; let us all share one purse\" - my son, do not walk the road with them or set foot upon their path." - Proverbs 1: 1 - 15 ',
        ' "Hallelujah! Praise GOD in His temple in heaven. Praise Him in His temple on earth. Praise Him for His mighty achievements; praise Him for His transcendent greatness. Praise Him with blasts of the trumpet; praise Him with lyre and harp. Praise Him with drums and dancing; praise Him with strings and flutes. Praise Him with clashing cymbals; praise Him with clanging cymbals. Let everything that has breath praise the LORD. Hallelujah!" - Psalm 150 ',
        ' "I thank CHRIST JESUS our LORD, who has strengthened me, that He considered me faithful and appointed me to service. I was formerly a blasphemer, a persecutor, and a violent man; yet because I had acted in ignorance and unbelief, I was shown mercy. And the grace of our LORD overflowed to me, along with the faith and love that are in CHRIST JESUS. This is a trustworthy saying, worthy of full acceptance: CHRIST JESUS came into the world to save sinners, of whom I am the worst. But, for this very reason I was shown mercy, so that in me, the worst of sinners; CHRIST JESUS might display His perfect patience as an example to those who would believe in Him for eternal life. Now to the King eternal, immortal, and invisible, the only GOD; be honor and glory forever and ever. Amen." - 1 Timothy 1:12 - 17 ',
        ' "Bless the LORD, O my soul, and all that is within me, bless His holy name. Bless the LORD, O my soul, and do not forget all His kind deeds. He who forgives all your iniquities, and heals all your diseases, who redeems your life from the pit and crowns you with loving devotion and compassion, who satisfies you with good things, so that your youth is renewed like the eagle\'s. The LORD executes righteousness and justice for all the oppressed. He made known His ways to Moses, His deeds to the people of Israel. The LORD is compassionate and gracious, slow to anger, abounding in loving devotion. He will not always accuse us, nor harbor His anger forever. He has not dealt with us according to our sins or repaid us according to our iniquities. For as high as the heavens are above the earth, so great is His loving devotion for those who fear Him. As far as the east is from the west, so far has He removed our transgressions from us. As a father has compassion on his children, so the LORD has compassion on those who fear Him. For He knows our frame; He is mindful that we are dust. As for man, his days are like grass - he blooms like a flower of the field; when the wind passes over it, it vanishes, and its place remembers it no more. But from everlasting to everlasting, the loving devotion of the LORD extends to those who fear Him, and His righteousness to their children\'s children - to those who keep His covenant and remember to obey His precepts. The LORD has established His throne in heaven, and His kingdom rules over all. Bless the LORD, all His angles mighty in strength, who carry out His word, who hearken to the voice of His command. Bless the LORD, all His hosts, you servants who do His will. Bless the LORD, all His works in all places of His dominion. Bless the LORD, O my soul!" - Psalm 103 ',
        ' "Paul (Samuel Dominic Chukwuemeka), a servant of JESUS CHRIST, called to be an apostle, and set apart for the gospel of GOD, the gospel He promised beforehand through His prophets in the Holy Scriptures, regarding His Son, who was a descendant of David according to the flesh, and who through the Spirit of holiness was declared with power to be the SON of GOD by His resurrection from the dead: JESUS CHRIST our LORD. Through Him and on behalf of His name, we received grace and apostleship to call all those among the Gentiles to the obedience that comes from faith. And you also are among those who are called to belong to JESUS CHRIST. To all in Rome (on earth) who are loved by GOD and called to be saints: Grace and peace to you from GOD our FATHER and the LORD JESUS CHRIST." - Romans 1:1 - 7 ',
        ' "Blessed is the man who does not walk in the counsel of the wicked, or set foot on the path of sinners, or sit in the seat of mockers. But his delight is in the law of the LORD, and on His law he meditates day and night. He is like a tree planted by streams of water, yielding its fruit in season, whose leaf does not wither, and who prospers in all he does, Not so for the wicked! For they are like chaff driven off by the wind. Therefore the wicked will not stand in the judgment, nor sinners in the assembly of the righteous. For the LORD guards the path of the righteous, but the way of the wicked will perish." - Psalm 1:1 - 6 ',
        ' "Remind the believers to be subject to \"good\" rulers and authorities, to be obedient and ready for every good work, to malign no one, and to be peaceable and gentle, showing full consideration to everyone. For at one time we too were foolish, disobedient, led astray, and enslaved to all sorts of desires and pleasures - living in malice and envy, hateful, and hating one another. But when the kindness of GOD our SAVIOR and His love for mankind appeared, He saved us; not by the righteous deeds we had done, but according to His mercy, through the washing of new birth and renewal by the HOLY SPIRIT. This is the SPIRIT He poured out on us abundantly through JESUS CHRIST our SAVIOR, so that having been justified by His grace, we would become heirs with the hope of eternal life. This saying is trustworthy. And I want you to emphasize these things, so that those who have believed GOD will take care to devote themselves to good deeds. These things are excellent and profitable for the people." - Titus 3:1 - 8 ',
        ' "O LORD, our GOD; how majestic is Your Name in all the earth! You have set Your glory above the heavens. From the mouths of children and infants, You have ordained praise on account of Your adversaries to silence the enemy and avenger. When I behold Your heavens, the work of Your fingers, the moon and the stars, which You have set in place - what is man that You are mindful of him, or the son of man that You care for him? You have made him a little lower than the angels; You crowned him with glory and honor. You made him ruler of the works of Your Hands; You have placed everything under his feet: all sheep and oxen, and even the beasts of the field, the birds of the air and the fish of the sea, all that swim the paths of the seas. O LORD, our GOD; how majestic is Your Name in all the earth!" - Psalm 8 ',
        ' "Paul (Samuel Dominic Chukwuemeka), an apostle of CHRIST JESUS by the will of GOD; To the saints in Ephesus (all over the world), the faithful in CHRIST JESUS: Grace and peace to you from GOD our FATHER and the LORD JESUS CHRIST. Blessed be the GOD and FATHER of our LORD JESUS CHRIST, who has blessed us in CHRIST with every spiritual blessing in the heavenly realms. For He chose us in Him before the foundation of the world to be holy and blameless in His presence. In love He predestined us for adoption as His sons through JESUS CHRIST, according to the good pleasure of His will, to the praise of His glorious grace, which He has freely given us in the Beloved ONE. In Him we have redemption through His blood, the forgiveness of our trespasses, according to the riches of His grace, that He lavished on us with all wisdom and understanding. And He has made known to us the mystery of His will according to His good pleasure, which He purposed in CHRIST JESUS as a plan for the fullness of time, to bring all things in heaven and on earth together in CHRIST. In Him we were also chosen as GOD\'s own, having been predestined according to the plan of Him who works out everything by the counsel of His will, in order that we, who were the first to hope in CHRIST, would be for the praise of His glory. And in Him, having heard and believed the word of truth - the gospel of your salvation - you were sealed with the promised HOLY SPIRIT, who is the pledge of our inheritance until the redemption of those who are GOD\'s possession, to the praise of His glory." - Ephesians 1:1 - 14 ',
        ' "O LORD, who may abide in Your tent? Who may dwell on Your holy hill? He who walks with integrity and practices righteousness, who speaks the truth from his heart, who has no slander on his tongue, who does no harm to his neighbor, who casts no scorn on his friend, who despises the vile but honors those who fear the LORD, who does not revise a costly oath, who lends his money without interest and refuses a bribe against the innocent. He who does these things will never be shaken." - Psalm 15 ',
        ' "For we brought nothing into the world, and neither can we carry anything out of it. But if we have food and clothing, we will be content with these. Those who want to be rich, however, fall into temptation and become ensnared by many foolish and harmful desires that plunge them into ruin and destruction. For the love of money is the root of all kinds of evil. By craving it, some have wandered away from the faith and pierced themselves with many sorrows. But you, O man of GOD, flee from these things and pursue righteousness, godliness, faith, love, perseverance, and gentleness. Fight the good fight of the faith. Take hold of the eternal life to which you were called when you made the good confession before many witnesses. I charge you in the presence of GOD, who gives life to all things, and of CHRIST JESUS, who made the good confession in His testimony before pontius pilate. Keep this commandment without stain or reproach until the appearance of our LORD JESUS CHRIST, which GOD will bring about in His own time - He who is blessed and the only Sovereign ONE, the KING of kings and the LORD of lords. He alone is immortal and dwells in unapproachable light. No one has ever seen Him, nor can anyone see Him. To Him be honor and eternal dominion! Amen." - 1 Timothy 6:7 - 16 ',
        ' "Preserve me, O GOD, for in You I take refuge. I said to the LORD, \"You are my LORD; apart from You I have no good thing.\" ... ... ... The LORD is my chosen portion and my cup; You have made my lot secure. The lines of my boundary have fallen in pleasant places; surely my inheritance is delightful. I will bless the LORD who counsels me; even at night my conscience instructs me. I have set the LORD always before me. Because He is at my right hand, I will not be shaken. Therefore my heart is glad and my tongue rejoices; my body also will dwell securely. For You will not abandon my soul to sheol, nor will You let Your Holy One see decay. You have made known to me the path of life; You will fill me with joy in Your presence, with eternal pleasures at Your right hand." - Psalm 16:1 - 2, 5 - 11 ',
        ' "Instruct those who are rich in the present age not to be conceited and not to put their hope in the uncertainty of wealth, but in GOD, who richly provides all things for us to enjoy. Instruct them to do good, to be rich in good works, and to be generous and ready to share, treasuring up for themselves a firm foundation for the future, so that they may take hold of that which is truly life." - 1 Timothy 6:17 - 19 ',
        ' "May the LORD answer you in the day of trouble (I would say always); may the Name of the GOD of Israel protect you. May He send you help from the sanctuary and sustain you from Zion. May He remember all your gifts and look favorably on your \"burnt\" offerings. May He give you the desires of your heart and make all your \"good\" plans succeed. May we shout for joy at your victory and raise a banner in the Name of our GOD. May the LORD sanction all your \"good\" petitions. Now I know that the LORD saves His anointed; He answers him from His holy heaven with the saving power of His right hand. Some trust in chariots and others in horses, but we trust in the Name of the LORD our GOD. They collapse and fall, but we rise up and stand firm. O LORD, save us. Answer us whenever we call." - Psalm 20 ',
        ' "Nevertheless, GOD\'s firm foundation stands, bearing this seal: \"The LORD knows those who are His,\" and, \"Everyone who calls on the Name of the LORD must turn away from iniquity.\" A large house contains not only vessels of gold and silver, but also of wood and clay. Some indeed are for honorable use, but others are for common use. So if anyone cleanses himself of what is unfit, he will be a vessel for honor: sanctified, useful to the MASTER, and prepared for every good work. Flee from youthful passions and pursue righteousness, faith, love, and peace, together with those who call on the LORD out of a pure heart. But reject foolish and ignorant speculation, for you know that it breeds quarreling. And a servant of the LORD must not be quarrelsome, but must be kind to everyone, able to teach, and forbearing. He must gently reprove those who oppose him, in the hope that GOD may grant them repentance leading to a knowledge of the truth." - 2 Timothy 2:19 - 25 ',
        ' "The LORD is my shepherd; I shall not want. He makes me lie down in green pastures; He leads me besides quiet waters. He restores my soul; He guides me in the paths of righteousness for the sake of His name. Even though I walk through the valley of the shadow of death, I will fear no evil, for You are with me; Your rod and Your staff, they comfort me. You prepare a table before me in the presence of my enemies. You anoint my head with oil; my cup overflows. Surely good ness and mercy will follow me all the days of my life, and I will dwell in the house of the LORD forever. Amen. - Psalm 23 ',
        ' "Love the LORD your GOD with all your heart, with all your soul, with all your mind, and with all your strength. Love your neighbor as yourself." - Mark 12: 30 - 31 '
        );  

var messages9 = dailyMessage[day - 1]; 

document.getElementById('messages9').innerHTML = messages9;
*/

var presentDate, presentHour, greeting;

presentDate = new Date();
presentDate.getDate();

presentHour = presentDate.getHours();

if (presentHour < 12) {
  greeting = "Good morning.";
} else if (presentHour >= 12 && presentHour < 16) {
  greeting = "Good afternoon.";
} else if (presentHour >= 16 && presentHour <= 24) {
  greeting = "Good evening.";
}

document.getElementById("greetings").innerHTML = greeting;

// Solutions to the Questions
function solutions(solution) {
  var e = document.getElementById(solution);
  if (e.style.display === "block" || e.style.display === "") e.style.display = "none";
  else e.style.display = "block";
}

// Answers to the Questions
function answers(answer) {
  var e = document.getElementById(answer);
  if (e.style.display === "block" || e.style.display === "") e.style.display = "none";
  else e.style.display = "block";
}
